#!/bin/bash

# Check if at least one input file argument is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 4 ]; then
    echo "Usage: $0 <input_file1> [input_file2] [input_file3] [input_file4]"
    exit 1
fi

# Run valgrind with the specified options and all input files
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./assembler "$@" 2>&1 | ccze -A
